In [1]:
import time
import random
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import pandas as pd
import subprocess
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC
import json
import os
import urllib.parse

In [34]:
options = Options()
options.add_argument("--start-maximized")  
options.add_experimental_option("detach", True)

# 크롬 드라이버 설정
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=options)



file = 'lawtalk_data.csv'

def get_data(page_number):

    numbers = []
    interests = []
    titles = []

    url = f'https://www.lawtalk.co.kr/qna/{page_number}'
    headers = {'User-Agent': 'Mozila/5.0'}
    driver.get(url)
    time.sleep(4)  

    soup = BeautifulSoup(driver.page_source, 'html.parser')


    elements = soup.find_all('div', class_='question directive qna-detail-page expanded')
    
    if not elements :
        return

    for element in elements:
        interest = element.find_all('span')[0].text.strip()
        title = element.find_all('h1')[0].text.strip()
        numbers.append(page_number)
        interests.append(interest)
        titles.append(title)
        
    if interests :
        df_category = pd.DataFrame({
            'number' : numbers,
            'interest': interests,
            'title': titles
        })

        is_file_exists = os.path.exists(file)

        df_category.to_csv(
            file,
            index=False,
            mode='a',
            header=not is_file_exists,
            encoding='utf-8-sig'
        )
        print(f'{page_number} 저장완료')


for page in range(443349, 560000):
    get_data(page)

443351 저장완료
443353 저장완료
443354 저장완료
443355 저장완료
443357 저장완료
443358 저장완료
443359 저장완료
443360 저장완료
443361 저장완료
443362 저장완료
443363 저장완료
443364 저장완료
443366 저장완료
443367 저장완료
443368 저장완료
443369 저장완료
443370 저장완료
443371 저장완료
443372 저장완료
443373 저장완료
443374 저장완료
443376 저장완료
443377 저장완료
443378 저장완료
443379 저장완료
443380 저장완료
443381 저장완료
443382 저장완료
443383 저장완료
443384 저장완료
443385 저장완료
443386 저장완료
443387 저장완료
443388 저장완료
443390 저장완료
443391 저장완료
443392 저장완료
443394 저장완료
443396 저장완료
443397 저장완료
443398 저장완료
443399 저장완료
443400 저장완료
443401 저장완료
443404 저장완료
443405 저장완료
443407 저장완료
443408 저장완료
443409 저장완료
443410 저장완료
443411 저장완료
443412 저장완료
443413 저장완료
443414 저장완료
443415 저장완료
443416 저장완료
443417 저장완료
443419 저장완료
443420 저장완료
443421 저장완료
443423 저장완료
443426 저장완료
443427 저장완료
443428 저장완료
443429 저장완료
443430 저장완료
443432 저장완료
443434 저장완료
443435 저장완료
443437 저장완료
443438 저장완료
443439 저장완료
443440 저장완료
443442 저장완료
443444 저장완료
443446 저장완료
443447 저장완료
443448 저장완료
443449 저장완료
443451 저장완료
443452 저장완료
443453 저장완료
443454 저장완료
443455 저장완료
443456 저장완료
443457 저장완료
443458 저장완료
443459 저장완료
443460 저장완료
443461 저장완료
443463 저장완료
443464 저장완료
443465 저장완료
443467 저장완료
443468 저장완료
443469 저장완료
443470 저장완료
443471 저장완료
443474 저장완료
443475 저장완료
443476 저장완료
443477 저장완료
443479 저장완료
443480 저장완료
443481 저장완료
443482 저장완료
443483 저장완료
443484 저장완료
443485 저장완료
443487 저장완료
443488 저장완료
443489 저장완료
443490 저장완료
443491 저장완료
443493 저장완료
443494 저장완료
443495 저장완료
443496 저장완료
443497 저장완료
443498 저장완료
443499 저장완료
443500 저장완료
443501 저장완료
443502 저장완료
443503 저장완료
443505 저장완료
443508 저장완료
443509 저장완료
443510 저장완료
443511 저장완료
443515 저장완료
443519 저장완료
443520 저장완료
443522 저장완료
443523 저장완료
443524 저장완료
443525 저장완료
443526 저장완료
443528 저장완료
443529 저장완료
443530 저장완료
443531 저장완료
443532 저장완료
443533 저장완료
443534 저장완료
443536 저장완료
443537 저장완료
443542 저장완료
443544 저장완료
443545 저장완료
443546 저장완료
443548 저장완료
443549 저장완료
443550 저장완료
443551 저장완료
443552 저장완료
443553 저장완료
443554 저장완료
443555 저장완료
443556 저장완료
443557 저장완료
443558 저장완료
443559 저장완료
443562 저장완료
443563 저장완료
443564 저장완료
443566 저장완료
443567 저장완료
443568 저장완료
443573 저장완료
443574 저장완료
443577 저장완료
443581 저장완료
443583 저장완료
443584 저장완료
443585 저장완료
443586 저장완료
443587 저장완료
443588 저장완료
443590 저장완료
443591 저장완료
443592 저장완료
443593 저장완료
443594 저장완료
443596 저장완료
443597 저장완료
443599 저장완료
443600 저장완료
443601 저장완료
443602 저장완료
443607 저장완료
443610 저장완료
443612 저장완료
443613 저장완료
443614 저장완료
443619 저장완료
443620 저장완료
443622 저장완료
443625 저장완료
443627 저장완료
443629 저장완료
443630 저장완료
443631 저장완료
443632 저장완료
443636 저장완료
443638 저장완료
443639 저장완료
443642 저장완료
443643 저장완료
443644 저장완료
443646 저장완료
443650 저장완료
443651 저장완료
443652 저장완료
443655 저장완료
443656 저장완료
443658 저장완료
443659 저장완료
443660 저장완료
443661 저장완료
443662 저장완료
443665 저장완료
443668 저장완료
443669 저장완료
443671 저장완료
443674 저장완료
443675 저장완료
443676 저장완료
443678 저장완료
443679 저장완료
443681 저장완료
443682 저장완료
443683 저장완료
443684 저장완료
443686 저장완료
443688 저장완료
443690 저장완료
443692 저장완료
443694 저장완료
443695 저장완료
443697 저장완료
443698 저장완료
443699 저장완료
443700 저장완료
443703 저장완료
443704 저장완료
443705 저장완료
443706 저장완료
443707 저장완료
443709 저장완료
443710 저장완료
443711 저장완료
443712 저장완료
443713 저장완료
443714 저장완료
443715 저장완료
443717 저장완료
443718 저장완료
443719 저장완료
443720 저장완료
443721 저장완료
443727 저장완료
443728 저장완료
443729 저장완료
443731 저장완료
443732 저장완료
443733 저장완료
443735 저장완료
443737 저장완료
443738 저장완료
443739 저장완료
443741 저장완료
443742 저장완료
443744 저장완료
443745 저장완료
443746 저장완료
443747 저장완료
443748 저장완료
443749 저장완료
443750 저장완료
443751 저장완료
443752 저장완료
443753 저장완료
443754 저장완료
443755 저장완료
443756 저장완료
443757 저장완료
443758 저장완료
443759 저장완료
443760 저장완료
443761 저장완료
443762 저장완료
443763 저장완료
443764 저장완료
443765 저장완료
443766 저장완료
443767 저장완료
443768 저장완료
443770 저장완료
443771 저장완료
443772 저장완료
443774 저장완료
443775 저장완료
443776 저장완료
443777 저장완료
443779 저장완료
443780 저장완료
443782 저장완료
443783 저장완료
443784 저장완료
443785 저장완료
443787 저장완료
443788 저장완료
443790 저장완료
443791 저장완료
443792 저장완료
443793 저장완료
443794 저장완료
443796 저장완료
443797 저장완료
443799 저장완료
443800 저장완료
443801 저장완료
443805 저장완료
443806 저장완료
443807 저장완료
443808 저장완료
443809 저장완료
443810 저장완료
443811 저장완료
443812 저장완료
443813 저장완료
443814 저장완료
443815 저장완료
443817 저장완료
443818 저장완료
443820 저장완료
443822 저장완료
443824 저장완료
443825 저장완료
443827 저장완료
443828 저장완료
443829 저장완료
443830 저장완료
443831 저장완료
443832 저장완료
443833 저장완료
443835 저장완료
443838 저장완료
443839 저장완료
443840 저장완료
443841 저장완료
443842 저장완료
443843 저장완료
443844 저장완료
443848 저장완료
443850 저장완료
443851 저장완료
443854 저장완료
443856 저장완료
443857 저장완료
443858 저장완료
443859 저장완료
443860 저장완료
443861 저장완료
443862 저장완료
443863 저장완료
443864 저장완료
443866 저장완료
443867 저장완료
443868 저장완료
443869 저장완료
443870 저장완료
443873 저장완료
443874 저장완료
443875 저장완료
443878 저장완료
443879 저장완료
443880 저장완료
443881 저장완료
443882 저장완료
443883 저장완료
443884 저장완료
443885 저장완료
443887 저장완료
443890 저장완료
443891 저장완료
443893 저장완료
443894 저장완료
443896 저장완료
443898 저장완료
443899 저장완료
443900 저장완료
443901 저장완료
443902 저장완료
443905 저장완료
443906 저장완료
443909 저장완료
443910 저장완료
443912 저장완료
443914 저장완료
443916 저장완료
443917 저장완료
443919 저장완료
443920 저장완료
443923 저장완료
443926 저장완료
443927 저장완료
443928 저장완료
443929 저장완료
443935 저장완료
443936 저장완료
443938 저장완료
443940 저장완료
443942 저장완료
443943 저장완료
443946 저장완료
443951 저장완료
443953 저장완료
443956 저장완료
443959 저장완료
443960 저장완료
443961 저장완료
443964 저장완료
443966 저장완료
443967 저장완료
443968 저장완료
443971 저장완료
443972 저장완료
443973 저장완료
443974 저장완료
443976 저장완료
443977 저장완료
443980 저장완료
443984 저장완료
443985 저장완료
443986 저장완료
443987 저장완료
443989 저장완료
443991 저장완료
443992 저장완료
443993 저장완료
443995 저장완료
443996 저장완료
443998 저장완료
443999 저장완료
444001 저장완료
444002 저장완료
444003 저장완료
444005 저장완료
444006 저장완료
444007 저장완료
444013 저장완료
444015 저장완료
444018 저장완료
444020 저장완료
444026 저장완료
444028 저장완료
444031 저장완료
444032 저장완료
444033 저장완료
444034 저장완료
444036 저장완료
444037 저장완료
444038 저장완료
444040 저장완료
444041 저장완료
444042 저장완료
444043 저장완료
444045 저장완료
444046 저장완료
444049 저장완료
444050 저장완료
444051 저장완료
444052 저장완료
444053 저장완료
444054 저장완료
444055 저장완료
444056 저장완료
444057 저장완료
444058 저장완료
444061 저장완료
444062 저장완료
444064 저장완료
444065 저장완료
444067 저장완료
444068 저장완료
444069 저장완료
444071 저장완료
444073 저장완료
444074 저장완료
444076 저장완료
444077 저장완료
444078 저장완료
444079 저장완료
444080 저장완료
444082 저장완료
444083 저장완료
444084 저장완료
444086 저장완료
444093 저장완료
444094 저장완료
444095 저장완료
444096 저장완료
444098 저장완료
444099 저장완료
444100 저장완료
444101 저장완료
444102 저장완료
444104 저장완료
444105 저장완료
444106 저장완료
444107 저장완료
444108 저장완료
444109 저장완료
444110 저장완료
444111 저장완료
444112 저장완료
444114 저장완료
444115 저장완료
444116 저장완료
444117 저장완료
444118 저장완료
444119 저장완료
444120 저장완료
444121 저장완료
444122 저장완료
444123 저장완료
444124 저장완료
444127 저장완료
444128 저장완료
444129 저장완료
444130 저장완료
444131 저장완료
444132 저장완료
444133 저장완료
444136 저장완료
444137 저장완료
444138 저장완료
444139 저장완료
444142 저장완료
444144 저장완료
444145 저장완료
444146 저장완료
444147 저장완료
444149 저장완료
444151 저장완료
444153 저장완료
444154 저장완료
444156 저장완료
444157 저장완료
444158 저장완료
444160 저장완료
444161 저장완료
444163 저장완료
444164 저장완료
444165 저장완료
444166 저장완료
444168 저장완료
444169 저장완료
444172 저장완료
444175 저장완료
444176 저장완료
444177 저장완료
444178 저장완료
444179 저장완료
444181 저장완료
444183 저장완료
444186 저장완료
444189 저장완료
444190 저장완료
444191 저장완료
444192 저장완료
444193 저장완료
444194 저장완료
444195 저장완료
444198 저장완료
444200 저장완료
444201 저장완료
444202 저장완료
444203 저장완료
444208 저장완료
444209 저장완료
444212 저장완료
444213 저장완료
444217 저장완료
444218 저장완료
444220 저장완료
444221 저장완료
444226 저장완료
444228 저장완료
444229 저장완료
444233 저장완료
444238 저장완료
444240 저장완료
444242 저장완료
444243 저장완료
444244 저장완료
444248 저장완료
444250 저장완료
444251 저장완료
444252 저장완료
444256 저장완료
444257 저장완료
444258 저장완료
444265 저장완료
444266 저장완료
444269 저장완료
444272 저장완료
444273 저장완료
444274 저장완료
444275 저장완료
444276 저장완료
444277 저장완료
444278 저장완료
444279 저장완료
444281 저장완료
444284 저장완료
444285 저장완료
444287 저장완료
444288 저장완료
444289 저장완료
444291 저장완료
444292 저장완료
444294 저장완료
444295 저장완료
444296 저장완료
444297 저장완료
444301 저장완료
444303 저장완료
444304 저장완료
444305 저장완료
444306 저장완료
444308 저장완료
444309 저장완료
444310 저장완료
444312 저장완료
444314 저장완료
444315 저장완료
444317 저장완료
444321 저장완료
444323 저장완료
444325 저장완료
444326 저장완료
444328 저장완료
444329 저장완료
444330 저장완료
444332 저장완료
444333 저장완료
444334 저장완료
444337 저장완료
444338 저장완료
444340 저장완료
444344 저장완료
444345 저장완료
444346 저장완료
444347 저장완료
444348 저장완료
444349 저장완료
444351 저장완료
444352 저장완료
444353 저장완료
444354 저장완료
444355 저장완료
444356 저장완료
444357 저장완료
444358 저장완료
444360 저장완료
444361 저장완료
444362 저장완료
444363 저장완료
444365 저장완료
444366 저장완료
444367 저장완료
444368 저장완료
444369 저장완료
444370 저장완료
444373 저장완료
444374 저장완료
444375 저장완료
444376 저장완료
444377 저장완료
444378 저장완료
444379 저장완료
444380 저장완료
444381 저장완료
444382 저장완료
444383 저장완료
444384 저장완료
444386 저장완료
444387 저장완료
444388 저장완료
444389 저장완료
444390 저장완료
444391 저장완료
444392 저장완료
444393 저장완료
444394 저장완료
444396 저장완료
444397 저장완료
444399 저장완료
444402 저장완료
444403 저장완료
444404 저장완료
444406 저장완료
444407 저장완료
444409 저장완료
444414 저장완료
444416 저장완료
444417 저장완료
444420 저장완료
444422 저장완료
444424 저장완료
444426 저장완료
444427 저장완료
444428 저장완료
444430 저장완료
444431 저장완료
444434 저장완료
444436 저장완료
444437 저장완료
444438 저장완료
444440 저장완료
444442 저장완료
444443 저장완료
444444 저장완료
444446 저장완료
444447 저장완료
444448 저장완료
444449 저장완료
444450 저장완료
444451 저장완료
444452 저장완료
444453 저장완료
444454 저장완료
444455 저장완료
444456 저장완료
444458 저장완료
444459 저장완료
444460 저장완료
444461 저장완료
444464 저장완료
444466 저장완료
444467 저장완료
444468 저장완료
444469 저장완료
444470 저장완료
444471 저장완료
444472 저장완료
444473 저장완료
444475 저장완료
444477 저장완료
444479 저장완료
444480 저장완료
444481 저장완료
444482 저장완료
444484 저장완료
444486 저장완료
444487 저장완료
444488 저장완료
444489 저장완료
444490 저장완료
444491 저장완료
444492 저장완료
444493 저장완료
444494 저장완료
444496 저장완료
444497 저장완료
444498 저장완료
444499 저장완료
444500 저장완료
444502 저장완료
444503 저장완료
444504 저장완료
444505 저장완료
444506 저장완료
444507 저장완료
444508 저장완료
444509 저장완료
444510 저장완료
444511 저장완료
444512 저장완료
444513 저장완료
444516 저장완료
444517 저장완료
444518 저장완료
444519 저장완료
444520 저장완료
444521 저장완료
444523 저장완료
444524 저장완료
444525 저장완료
444526 저장완료
444527 저장완료
444528 저장완료
444529 저장완료
444530 저장완료
444533 저장완료
444538 저장완료
444539 저장완료
444540 저장완료
444541 저장완료
444542 저장완료
444543 저장완료
444545 저장완료
444546 저장완료
444547 저장완료
444548 저장완료
444550 저장완료
444552 저장완료
444553 저장완료
444554 저장완료
444555 저장완료
444556 저장완료
444557 저장완료
444558 저장완료
444559 저장완료
444561 저장완료
444565 저장완료
444566 저장완료
444567 저장완료
444570 저장완료
444571 저장완료
444572 저장완료
444573 저장완료
444574 저장완료
444576 저장완료
444577 저장완료
444578 저장완료
444579 저장완료
444580 저장완료
444581 저장완료
444583 저장완료
444584 저장완료
444585 저장완료
444586 저장완료
444587 저장완료
444589 저장완료
444591 저장완료
444592 저장완료
444593 저장완료
444594 저장완료
444597 저장완료
444598 저장완료
444599 저장완료
444601 저장완료
444602 저장완료
444603 저장완료
444604 저장완료
444606 저장완료
444611 저장완료
444612 저장완료
444614 저장완료
444615 저장완료
444616 저장완료
444618 저장완료
444620 저장완료
444621 저장완료
444623 저장완료
444624 저장완료
444625 저장완료
444627 저장완료
444628 저장완료
444632 저장완료
444634 저장완료
444636 저장완료
444637 저장완료
444640 저장완료
444644 저장완료
444645 저장완료
444646 저장완료
444647 저장완료
444648 저장완료
444649 저장완료
444654 저장완료
444659 저장완료
444663 저장완료
444664 저장완료
444666 저장완료
444671 저장완료
444673 저장완료
444674 저장완료
444675 저장완료
444676 저장완료
444677 저장완료
444680 저장완료
444681 저장완료
444686 저장완료
444687 저장완료
444689 저장완료
444690 저장완료
444696 저장완료
444697 저장완료
444699 저장완료
444701 저장완료
444703 저장완료
444705 저장완료
444706 저장완료
444707 저장완료
444712 저장완료
444713 저장완료
444715 저장완료
444717 저장완료
444718 저장완료
444721 저장완료
444722 저장완료
444723 저장완료
444724 저장완료
444725 저장완료
444726 저장완료
444728 저장완료
444729 저장완료
444730 저장완료
444732 저장완료
444733 저장완료
444734 저장완료
444735 저장완료
444736 저장완료
444740 저장완료
444741 저장완료
444742 저장완료
444743 저장완료
444745 저장완료
444746 저장완료
444747 저장완료
444748 저장완료
444749 저장완료
444750 저장완료
444751 저장완료
444752 저장완료
444753 저장완료
444754 저장완료
444755 저장완료
444756 저장완료
444757 저장완료
444759 저장완료
444760 저장완료
444761 저장완료
444763 저장완료
444767 저장완료
444769 저장완료
444770 저장완료
444772 저장완료
444774 저장완료
444781 저장완료
444782 저장완료
444784 저장완료
444785 저장완료
444788 저장완료
444789 저장완료
444791 저장완료
444792 저장완료
444793 저장완료
444796 저장완료
444798 저장완료
444799 저장완료
444801 저장완료
444802 저장완료
444805 저장완료
444806 저장완료
444807 저장완료
444808 저장완료
444809 저장완료
444810 저장완료
444811 저장완료
444817 저장완료
444818 저장완료
444819 저장완료
444820 저장완료
444824 저장완료
444826 저장완료
444829 저장완료
444832 저장완료
444833 저장완료
444834 저장완료
444836 저장완료
444837 저장완료
444838 저장완료
444844 저장완료
444846 저장완료
444847 저장완료
444848 저장완료
444851 저장완료
444852 저장완료
444854 저장완료
444855 저장완료
444858 저장완료
444859 저장완료
444860 저장완료
444861 저장완료
444862 저장완료
444863 저장완료
444866 저장완료
444868 저장완료
444869 저장완료
444870 저장완료
444873 저장완료
444874 저장완료
444878 저장완료
444881 저장완료
444885 저장완료
444888 저장완료
444889 저장완료
444891 저장완료
444895 저장완료
444897 저장완료
444898 저장완료
444901 저장완료
444902 저장완료
444905 저장완료
444906 저장완료
444907 저장완료
444913 저장완료
444914 저장완료
444917 저장완료
444918 저장완료
444919 저장완료
444920 저장완료
444921 저장완료
444922 저장완료
444923 저장완료
444925 저장완료
444927 저장완료
444929 저장완료
444932 저장완료
444933 저장완료
444934 저장완료
444935 저장완료
444936 저장완료
444938 저장완료
444940 저장완료
444944 저장완료
444946 저장완료
444947 저장완료
444950 저장완료
444951 저장완료
444956 저장완료
444957 저장완료
444958 저장완료
444959 저장완료
444960 저장완료
444965 저장완료
444966 저장완료
444968 저장완료
444972 저장완료
444973 저장완료
444974 저장완료
444976 저장완료
444978 저장완료
444979 저장완료
444980 저장완료
444981 저장완료
444983 저장완료
444984 저장완료
444985 저장완료
444988 저장완료
444990 저장완료
444991 저장완료
444992 저장완료
444994 저장완료
444996 저장완료
444997 저장완료
444998 저장완료
444999 저장완료
445000 저장완료
445001 저장완료
445002 저장완료
445004 저장완료
445005 저장완료
445006 저장완료
445007 저장완료
445008 저장완료
445009 저장완료
445010 저장완료
445011 저장완료
445012 저장완료
445013 저장완료
445018 저장완료
445019 저장완료
445021 저장완료
445022 저장완료
445023 저장완료
445024 저장완료
445025 저장완료
445026 저장완료
445027 저장완료
445028 저장완료
445030 저장완료
445031 저장완료
445032 저장완료
445034 저장완료
445035 저장완료
445036 저장완료
445037 저장완료
445038 저장완료
445039 저장완료
445042 저장완료
445043 저장완료
445045 저장완료
445047 저장완료
445049 저장완료
445050 저장완료
445051 저장완료
445053 저장완료
445055 저장완료
445056 저장완료
445061 저장완료
445062 저장완료
445063 저장완료
445065 저장완료
445066 저장완료
445068 저장완료
445069 저장완료
445070 저장완료
445072 저장완료
445073 저장완료
445074 저장완료
445075 저장완료
445076 저장완료
445077 저장완료
445078 저장완료
445079 저장완료
445080 저장완료
445082 저장완료
445083 저장완료
445084 저장완료
445085 저장완료
445086 저장완료
445087 저장완료
445088 저장완료
445089 저장완료
445090 저장완료
445091 저장완료
445092 저장완료
445093 저장완료
445095 저장완료
445096 저장완료
445097 저장완료
445099 저장완료
445100 저장완료
445101 저장완료
445103 저장완료
445104 저장완료
445105 저장완료
445106 저장완료
445107 저장완료
445110 저장완료
445111 저장완료
445113 저장완료
445114 저장완료
445115 저장완료
445116 저장완료
445117 저장완료
445118 저장완료
445120 저장완료
445121 저장완료
445122 저장완료
445123 저장완료
445125 저장완료
445126 저장완료
445128 저장완료
445129 저장완료
445130 저장완료
445131 저장완료
445132 저장완료
445134 저장완료
445138 저장완료
445141 저장완료
445142 저장완료
445143 저장완료
445144 저장완료
445145 저장완료
445146 저장완료
445148 저장완료
445149 저장완료
445152 저장완료
445154 저장완료
445155 저장완료
445156 저장완료
445157 저장완료
445159 저장완료
445160 저장완료
445165 저장완료
445166 저장완료
445168 저장완료
445170 저장완료
445172 저장완료
445173 저장완료
445174 저장완료
445176 저장완료
445177 저장완료
445178 저장완료
445179 저장완료
445180 저장완료
445182 저장완료
445183 저장완료
445184 저장완료
445187 저장완료
445188 저장완료
445190 저장완료
445191 저장완료
445194 저장완료
445198 저장완료
445203 저장완료
445206 저장완료
445207 저장완료
445210 저장완료
445211 저장완료
445212 저장완료
445213 저장완료
445216 저장완료
445217 저장완료
445219 저장완료
445221 저장완료
445224 저장완료
445226 저장완료
445227 저장완료
445228 저장완료
445229 저장완료
445230 저장완료
445231 저장완료
445232 저장완료
445233 저장완료
445234 저장완료
445235 저장완료
445236 저장완료
445237 저장완료
445238 저장완료
445240 저장완료
445241 저장완료
445243 저장완료
445246 저장완료
445247 저장완료
445248 저장완료
445249 저장완료
445250 저장완료
445251 저장완료
445252 저장완료
445253 저장완료
445254 저장완료
445255 저장완료
445256 저장완료
445257 저장완료
445259 저장완료
445260 저장완료
445263 저장완료
445264 저장완료
445265 저장완료
445266 저장완료
445269 저장완료
445270 저장완료
445271 저장완료
445272 저장완료
445275 저장완료
445276 저장완료
445277 저장완료
445279 저장완료
445280 저장완료
445281 저장완료
445282 저장완료
445283 저장완료
445284 저장완료
445285 저장완료
445286 저장완료
445287 저장완료
445288 저장완료
445289 저장완료
445290 저장완료
445292 저장완료
445294 저장완료
445295 저장완료
445296 저장완료
445297 저장완료
445298 저장완료
445299 저장완료
445300 저장완료
445302 저장완료
445303 저장완료
445304 저장완료
445305 저장완료
445307 저장완료
445308 저장완료
445309 저장완료
445310 저장완료
445312 저장완료
445313 저장완료
445315 저장완료
445316 저장완료
445320 저장완료
445323 저장완료
445324 저장완료
445325 저장완료
445326 저장완료
445327 저장완료
445329 저장완료
445330 저장완료
445331 저장완료
445333 저장완료
445334 저장완료
445335 저장완료
445336 저장완료
445337 저장완료
445338 저장완료
445339 저장완료
445340 저장완료
445341 저장완료
445343 저장완료
445344 저장완료
445345 저장완료
445346 저장완료
445347 저장완료
445350 저장완료
445351 저장완료
445352 저장완료
445353 저장완료
445354 저장완료
445355 저장완료
445356 저장완료
445357 저장완료
445358 저장완료
445359 저장완료
445360 저장완료
445361 저장완료
445362 저장완료
445364 저장완료
445365 저장완료
445366 저장완료
445368 저장완료
445369 저장완료
445370 저장완료
445371 저장완료
445372 저장완료
445373 저장완료
445374 저장완료
445376 저장완료
445377 저장완료
445378 저장완료
445379 저장완료
445380 저장완료
445381 저장완료
445382 저장완료
445383 저장완료
445384 저장완료
445385 저장완료
445389 저장완료
445390 저장완료
445391 저장완료
445392 저장완료
445393 저장완료
445394 저장완료
445395 저장완료
445396 저장완료
445397 저장완료
445398 저장완료
445399 저장완료
445400 저장완료
445401 저장완료
445402 저장완료
445403 저장완료
445404 저장완료
445407 저장완료
445410 저장완료
445411 저장완료
445412 저장완료
445413 저장완료
445414 저장완료
445415 저장완료
445416 저장완료
445417 저장완료
445418 저장완료
445419 저장완료
445420 저장완료
445421 저장완료
445422 저장완료
445423 저장완료
445424 저장완료
445425 저장완료
445427 저장완료
445428 저장완료
445429 저장완료
445430 저장완료
445431 저장완료
445432 저장완료
445433 저장완료
445434 저장완료
445435 저장완료
445438 저장완료
445439 저장완료
445440 저장완료
445441 저장완료
445442 저장완료
445443 저장완료
445444 저장완료
445446 저장완료
445447 저장완료
445448 저장완료
445449 저장완료
445450 저장완료
445451 저장완료
445452 저장완료
445453 저장완료
445454 저장완료
445455 저장완료
445456 저장완료
445457 저장완료
445458 저장완료
445459 저장완료
445460 저장완료
445461 저장완료
445462 저장완료
445463 저장완료
445464 저장완료
445465 저장완료
445466 저장완료
445467 저장완료
445468 저장완료
445469 저장완료
445471 저장완료
445472 저장완료
445473 저장완료
445474 저장완료
445475 저장완료
445477 저장완료
445478 저장완료
445479 저장완료
445480 저장완료
445481 저장완료
445482 저장완료
445483 저장완료
445484 저장완료
445485 저장완료
445486 저장완료
445488 저장완료
445489 저장완료
445490 저장완료
445491 저장완료
445492 저장완료
445494 저장완료
445496 저장완료
445497 저장완료
445498 저장완료
445499 저장완료
445500 저장완료
445501 저장완료
445502 저장완료
445503 저장완료
445506 저장완료
445508 저장완료
445510 저장완료
445511 저장완료
445512 저장완료
445514 저장완료
445515 저장완료
445516 저장완료
445518 저장완료
445523 저장완료
445527 저장완료
445528 저장완료
445529 저장완료
445532 저장완료
445534 저장완료
445546 저장완료
445548 저장완료
445552 저장완료
445553 저장완료
445557 저장완료
445560 저장완료
445561 저장완료
445564 저장완료
445565 저장완료
445566 저장완료
445567 저장완료
445568 저장완료
445570 저장완료
445572 저장완료
445577 저장완료
445578 저장완료
445579 저장완료
445580 저장완료
445582 저장완료
445585 저장완료
445587 저장완료
445589 저장완료
445590 저장완료
445597 저장완료
445598 저장완료
445599 저장완료
445600 저장완료
445601 저장완료
445602 저장완료
445605 저장완료
445609 저장완료
445610 저장완료
445611 저장완료
445615 저장완료
445617 저장완료
445620 저장완료
445622 저장완료
445623 저장완료
445625 저장완료
445629 저장완료
445630 저장완료
445631 저장완료
445633 저장완료
445640 저장완료
445641 저장완료
445643 저장완료
445645 저장완료
445646 저장완료
445652 저장완료
445653 저장완료
445655 저장완료
445657 저장완료
445658 저장완료
445663 저장완료
445664 저장완료
445665 저장완료
445666 저장완료
445668 저장완료
445670 저장완료
445671 저장완료
445672 저장완료
445673 저장완료
445674 저장완료
445675 저장완료
445677 저장완료
445679 저장완료
445680 저장완료
445681 저장완료
445684 저장완료
445685 저장완료
445686 저장완료
445687 저장완료
445688 저장완료
445689 저장완료
445690 저장완료
445692 저장완료
445694 저장완료
445695 저장완료
445696 저장완료
445697 저장완료
445698 저장완료
445699 저장완료
445701 저장완료
445703 저장완료
445704 저장완료
445706 저장완료
445707 저장완료
445708 저장완료
445709 저장완료
445710 저장완료
445711 저장완료
445712 저장완료
445713 저장완료
445715 저장완료
445716 저장완료
445717 저장완료
445718 저장완료
445719 저장완료
445720 저장완료
445721 저장완료
445722 저장완료
445723 저장완료
445724 저장완료
445725 저장완료
445726 저장완료
445727 저장완료
445728 저장완료
445729 저장완료
445730 저장완료
445731 저장완료
445732 저장완료
445733 저장완료
445735 저장완료
445737 저장완료
445738 저장완료
445739 저장완료
445740 저장완료
445743 저장완료
445745 저장완료
445749 저장완료
445750 저장완료
445752 저장완료
445753 저장완료
445757 저장완료
445758 저장완료
445762 저장완료
445763 저장완료
445764 저장완료
445767 저장완료
445768 저장완료
445769 저장완료
445770 저장완료
445772 저장완료
445773 저장완료
445776 저장완료
445779 저장완료
445781 저장완료
445782 저장완료
445783 저장완료
445784 저장완료
445786 저장완료
445787 저장완료
445789 저장완료
445790 저장완료
445792 저장완료
445794 저장완료
445795 저장완료
445796 저장완료
445798 저장완료
445799 저장완료
445800 저장완료
445803 저장완료
445804 저장완료
445806 저장완료
445807 저장완료
445808 저장완료
445810 저장완료
445812 저장완료
445814 저장완료
445815 저장완료
445816 저장완료
445817 저장완료
445818 저장완료
445820 저장완료
445821 저장완료
445823 저장완료
445824 저장완료
445825 저장완료
445829 저장완료
445830 저장완료
445831 저장완료
445832 저장완료
445833 저장완료
445834 저장완료
445835 저장완료
445836 저장완료
445837 저장완료
445838 저장완료
445839 저장완료
445840 저장완료
445841 저장완료
445842 저장완료
445843 저장완료
445847 저장완료
445849 저장완료
445851 저장완료
445852 저장완료
445855 저장완료
445856 저장완료
445857 저장완료
445858 저장완료
445860 저장완료
445861 저장완료
445864 저장완료
445866 저장완료
445869 저장완료
445870 저장완료
445871 저장완료
445872 저장완료
445873 저장완료
445875 저장완료
445877 저장완료
445878 저장완료
445879 저장완료
445881 저장완료

KeyboardInterrupt:

In [35]:
df = pd.read_csv('lawtalk_data.csv')
df

       number     interest                          title
0      400000           이혼          이혼 후 재산분할 미지급 시 대처 방안
1      400001   명예훼손/모욕 일반          직장 내 성추행 사건에 대한 고소 준비
2      400002          임대차                 전세권 설정과 관련된 질문
3      400004         손해배상      폭행사건 피해자, 민사소송 가능성에 대한 상담
4      400008  폭행/협박/상해 일반      스토킹 및 협박 고소에 대한 우려와 대처 방안
...       ...          ...                            ...
37602  459335      고소/소송절차       빌려준 돈 제 삼자 고소 가능성에 대한 상담
37603  459336        회생/파산       전세사기 피해와 개인회생 가능성에 대한 상담
37604  459338     지식재산권/엔터  온라인 판매자에 의한 상표권 침해 가능성에 대한 상담
37605  459340        사기/공갈        오픈채팅 1대1 만남 후 불이익 경험 공유
37606  459341   명예훼손/모욕 일반      CCTV 열람과 개인정보보호 위반에 대한 질문

[37607 rows x 3 columns]

In [6]:
df

          number     interest                            title
0         430000           이혼            이혼 후 재산분할 미지급 시 대처 방안
1         430001   명예훼손/모욕 일반            직장 내 성추행 사건에 대한 고소 준비
2         430002          임대차                   전세권 설정과 관련된 질문
3         430004         손해배상        폭행사건 피해자, 민사소송 가능성에 대한 상담
4         430008  폭행/협박/상해 일반        스토킹 및 협박 고소에 대한 우려와 대처 방안
...          ...          ...                              ...
22575050  406522      고소/소송절차  아랫집에서의 층간소음 보복에 대한 조치 방안과 법적 대응
22575051  406520      고소/소송절차                상간녀 소장접수와 관련한 상담글
22575052  406521   명예훼손/모욕 일반           인스타 댓글로 인한 사이버명예훼손 가능성
22575053  406522      고소/소송절차  아랫집에서의 층간소음 보복에 대한 조치 방안과 법적 대응
22575054  406523    형사일반/기타범죄            스토킹 고소를 당한 경험에 대한 상담글

[22575055 rows x 3 columns]

In [19]:
df[df.duplicated(keep=False)]

       number     interest                              title
13235  421828        사기/공갈            형사 사건 위임장에 인감증명이 필요한가요?
13236  421828        사기/공갈            형사 사건 위임장에 인감증명이 필요한가요?
13237  421829           이혼     전업주부 재산분할 시 어떻게 정해야 하는지에 대한 안내
13238  421828        사기/공갈            형사 사건 위임장에 인감증명이 필요한가요?
13239  421829           이혼     전업주부 재산분할 시 어떻게 정해야 하는지에 대한 안내
...       ...          ...                                ...
13320  421837  폭행/협박/상해 일반       기간제 교사와 법적 효력: 학생의 폭력에 대한 대응
13321  421838           이혼       이혼시 상대방의 개인파산 신청과 재산분할 관련 질문
13322  421840    형사일반/기타범죄             동거 상대에게 빛을 줄 수 있는 방법은?
13323  421843  사이버 명예훼손/모욕  직장내 부적절한 메신저 대화 발견, 어떻게 대처해야 할까요?
13324  421846   성폭력/강제추행 등       준강제추행 사건에 대한 혐의없음 처분과 관련된 상담

[90 rows x 3 columns]

In [8]:
df.columns

Index(['number', 'interest', 'title'], dtype='object')

In [36]:
df[df['title'].isnull()]

       number interest title
14406  423772      작성됨   NaN
15083  424788      작성됨   NaN
15885  425930      작성됨   NaN
16518  426901      작성됨   NaN
19313  430888      작성됨   NaN
...       ...      ...   ...
35747  456653      작성됨   NaN
36055  457110      작성됨   NaN
36360  457608      작성됨   NaN
36531  457855      작성됨   NaN
36920  458434      작성됨   NaN

[81 rows x 3 columns]

In [37]:
df1 = df[~df['title'].isnull()]
df1

       number     interest                          title
0      400000           이혼          이혼 후 재산분할 미지급 시 대처 방안
1      400001   명예훼손/모욕 일반          직장 내 성추행 사건에 대한 고소 준비
2      400002          임대차                 전세권 설정과 관련된 질문
3      400004         손해배상      폭행사건 피해자, 민사소송 가능성에 대한 상담
4      400008  폭행/협박/상해 일반      스토킹 및 협박 고소에 대한 우려와 대처 방안
...       ...          ...                            ...
37602  459335      고소/소송절차       빌려준 돈 제 삼자 고소 가능성에 대한 상담
37603  459336        회생/파산       전세사기 피해와 개인회생 가능성에 대한 상담
37604  459338     지식재산권/엔터  온라인 판매자에 의한 상표권 침해 가능성에 대한 상담
37605  459340        사기/공갈        오픈채팅 1대1 만남 후 불이익 경험 공유
37606  459341   명예훼손/모욕 일반      CCTV 열람과 개인정보보호 위반에 대한 질문

[37526 rows x 3 columns]

In [38]:
df_d = df1[df1['number'].duplicated()]

In [39]:
df_d.sort_values(by='number', ascending=True)

Empty DataFrame
Columns: [number, interest, title]
Index: []

In [68]:
df2 = df1[~df1['title'].duplicated()]
df2

       number     interest                          title
0      400000           이혼          이혼 후 재산분할 미지급 시 대처 방안
1      400001   명예훼손/모욕 일반          직장 내 성추행 사건에 대한 고소 준비
2      400002          임대차                 전세권 설정과 관련된 질문
3      400004         손해배상      폭행사건 피해자, 민사소송 가능성에 대한 상담
4      400008  폭행/협박/상해 일반      스토킹 및 협박 고소에 대한 우려와 대처 방안
...       ...          ...                            ...
37602  459335      고소/소송절차       빌려준 돈 제 삼자 고소 가능성에 대한 상담
37603  459336        회생/파산       전세사기 피해와 개인회생 가능성에 대한 상담
37604  459338     지식재산권/엔터  온라인 판매자에 의한 상표권 침해 가능성에 대한 상담
37605  459340        사기/공갈        오픈채팅 1대1 만남 후 불이익 경험 공유
37606  459341   명예훼손/모욕 일반      CCTV 열람과 개인정보보호 위반에 대한 질문

[36938 rows x 3 columns]

In [6]:
df2[:10]

   number     interest                         title
0  430000           이혼         이혼 후 재산분할 미지급 시 대처 방안
1  430001   명예훼손/모욕 일반         직장 내 성추행 사건에 대한 고소 준비
2  430002          임대차                전세권 설정과 관련된 질문
3  430004         손해배상     폭행사건 피해자, 민사소송 가능성에 대한 상담
4  430008  폭행/협박/상해 일반     스토킹 및 협박 고소에 대한 우려와 대처 방안
5  400010      교통사고/도주     교통사고 책임보험 후미추돌 합의금에 대한 상담
6  400011          임대차               전세계약갱신 관련 자문 요청
7  400012  폭행/협박/상해 일반        폭행 관련 쌍방 성립 가능성에 대한 상담
8  400016      계약일반/매매  계약 체결 전 진행한 업무 보상 가능성에 대한 상담
9  400019          임대차         임대차보증금 반환 청구소송에 대한 질문

In [8]:
df2.loc[0,'number'] = 400000
df2.loc[1,'number'] = 400001
df2.loc[2,'number'] = 400002
df2.loc[3,'number'] = 400004
df2.loc[4,'number'] = 400008
df2

         number     interest                                  title
0        400000           이혼                  이혼 후 재산분할 미지급 시 대처 방안
1        400001   명예훼손/모욕 일반                  직장 내 성추행 사건에 대한 고소 준비
2        400002          임대차                         전세권 설정과 관련된 질문
3        400004         손해배상              폭행사건 피해자, 민사소송 가능성에 대한 상담
4        400008  폭행/협박/상해 일반              스토킹 및 협박 고소에 대한 우려와 대처 방안
...         ...          ...                                    ...
7951359  421820    건축/부동산 일반                     불법건축물 철거 요청에 대한 고민
7955345  421823     대여금/채권추심  빌려준 돈을 돌려받지 못하는 상황에서 사기죄 형사고소 가능여부 문의
7959332  421824      교통사고/도주                   미접촉 교통사고와 합의금에 대한 상담
7963320  421825     대여금/채권추심                채무불이행 사기로 고소 가능성에 대한 상담
7967309  421826      기타 재산범죄                 허위사실로 비방하는 사람을 고소하는 방법

[13235 rows x 3 columns]

In [69]:
df2.to_csv('lawtalk_data.csv', index=False)

In [70]:
df2.count()

number      36938
interest    36938
title       36938
dtype: int64

In [71]:
df2['interest'].nunique()

41

In [72]:
df2['interest'].value_counts()

interest
사기/공갈                3816
고소/소송절차              3741
임대차                  2937
손해배상                 2222
디지털 성범죄              2133
명예훼손/모욕 일반           1886
형사일반/기타범죄            1756
계약일반/매매              1521
기타 재산범죄              1428
이혼                   1368
폭행/협박/상해 일반          1361
대여금/채권추심             1324
성폭력/강제추행 등           1044
수사/체포/구속              957
교통사고/도주               924
사이버 명예훼손/모욕           880
상속                    749
건축/부동산 일반             733
미성년 대상 성범죄            725
소송/집행절차               672
기업법무                  627
노동/인사                 578
성매매                   413
횡령/배임                 400
회생/파산                 354
마약/도박                 326
음주/무면허                287
매매/소유권 등              256
가사 일반                 211
IT/개인정보               185
소년범죄/학교폭력             169
세금/행정/헌법              165
병역/군형법                152
지식재산권/엔터              135
금융/보험                 120
가압류/가처분               111
공증/내용증명/조합/국제문제 등     110
의료/식품의약                61
소비자/공정거래               60
재개발/재건축                40
지역                      1
Name: count, dtype: int64

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37526 entries, 0 to 37606
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   number    37526 non-null  int64
 1   interest  37526 non-null  object
 2   title     37526 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.1+ MB

In [46]:
df2.describe(include=object)

       interest               title
count     37526               37526
unique       41               36938
top       사기/공갈  명예훼손 고소 가능성에 대한 상담
freq       3899                  13

In [54]:
df3 = df2[df2['title'].duplicated(keep=False)]

In [58]:
df3 = df3.sort_values(by='number', ascending=True)

In [59]:
duplicates_mask = df3.duplicated(subset=['title'], keep=False)

In [60]:
df3_duplicates = df3[duplicates_mask]

In [67]:
df3.sort_values(by='title', ascending=True)

       number   interest                                      title
20989  433275    소송/집행절차  NET급여계약 후 이직 이후 연말정산 중간정산 환급금 미지급 시 해결 방안
20988  433274       손해배상  NET급여계약 후 이직 이후 연말정산 중간정산 환급금 미지급 시 해결 방안
24331  438350  형사일반/기타범죄                   가스라이팅으로 인한 고소 가능성에 대한 질문
13864  422832  형사일반/기타범죄                   가스라이팅으로 인한 고소 가능성에 대한 질문
10731  418083  형사일반/기타범죄                   가출 청소년과의 상황에 대한 법적 조언 요청
...       ...        ...                                        ...
13391  422084    기타 재산범죄                          횡령죄 고소 가능성에 대한 상담
32610  451906      횡령/배임                          횡령죄 고소 가능성에 대한 상담
5309   409441    계약일반/매매                          횡령죄 고소 가능성에 대한 상담
2316   404262      횡령/배임                              횡령죄 처벌에 대한 상담
2758   404996      횡령/배임                              횡령죄 처벌에 대한 상담

[1011 rows x 3 columns]

In [2]:
df = pd.read_csv('lawtalk_data.csv', encoding='utf-8')
df['interest'].unique()

array(['이혼', '명예훼손/모욕 일반', '임대차', '손해배상', '폭행/협박/상해 일반', '교통사고/도주',
       '계약일반/매매', '디지털 성범죄', '성폭력/강제추행 등', '기타 재산범죄', '대여금/채권추심',
       '형사일반/기타범죄', '사기/공갈', '건축/부동산 일반', '미성년 대상 성범죄', '고소/소송절차', '상속',
       '매매/소유권 등', '횡령/배임', '마약/도박', '사이버 명예훼손/모욕', '가사 일반', '지식재산권/엔터',
       '음주/무면허', '기업법무', '병역/군형법', '소년범죄/학교폭력', '노동/인사', '소송/집행절차', '성매매',
       '수사/체포/구속', 'IT/개인정보', '세금/행정/헌법', '회생/파산', '금융/보험',
       '공증/내용증명/조합/국제문제 등', '재개발/재건축', '의료/식품의약', '가압류/가처분', '소비자/공정거래'],
      dtype=object)